CREATE TABLE IF NOT EXISTS pokemon (
	ID INT(4) NOT NULL AUTO_INCREMENT,
	name VARCHAR(16) NOT NULL UNIQUE,
	height FLOAT NOT NULL,
	weight FLOAT NOT NULL,
	description VARCHAR(255) NOT NULL UNIQUE,
	base_xp SMALLINT(4) unsigned NOT NULL,
	sprite VARCHAR(255) NOT NULL UNIQUE,
	hp INT NOT NULL,
	atk INT NOT NULL,
	def INT NOT NULL,
	specialatk INT NOT NULL,
	specialdef INT NOT NULL,
	spd INT NOT NULL,
	male float,
	female float,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS abilities (
	ID INT NOT NULL AUTO_INCREMENT,
	normal VARCHAR(255),
	hidden VARCHAR(255),
	PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS relAbilitiesPokemon (
	ID INT NOT NULL AUTO_INCREMENT,
	pokemonID INT NOT NULL,
	abilityID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (pokemonID) REFERENCES pokemon(ID),
	FOREIGN KEY (abilityID) REFERENCES abilities(ID)
);


CREATE TABLE IF NOT EXISTS types (
	ID INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS relTypesPokemon (
	ID INT NOT NULL AUTO_INCREMENT,
	pokemonID INT NOT NULL,
	typeID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (pokemonID) REFERENCES pokemon(ID),
	FOREIGN KEY (typeID) REFERENCES types(ID)
);